# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://Carry.Us.Org
title: Carry.Us.Org
launchdate: August 2016
logo: img/carryusorg-logo-256.png
email: hello@Carry.Us.Org
author: Manuel Mejía
description: |
  Carry.Us.Org helps athletes fundraise for charitable causes 
  and build sustainable campaigns. #athletes4good @CarryUsOrg

copyright: 'Copyright &copy; 2015 Carry.Us.Org. All Rights Reserved.'
# credits: '<a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
include: [_data]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
favicon: /img/carryusorg-logo-256.png


social:
  - title: facebook
    url: https://www.facebook.com/carryusorg
  - title: twitter
    url: https://twitter.com/carryusorg
  - title: instagram
    url: https:instagram.com/carryusorg
  # - title: github
    # url: https://github.com/carryusorg

email:
  - hello@carry.us.org
