# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://Carry.Us.Org
title: Carry.Us.Org
launchdate: September 2016
logo: img/carryusorg-logo-256.png
email: hello@Carry.Us.Org
author: "Manuel Mejia, Nat Evory, Shannon Mejia"
description: |
  Carry.Us.Org helps athletes fundraise for charitable causes and finance their campaigns. #athletes4good @CarryUsOrg
image: http://carry.us.org/img/twin-peaks-runner.jpg

copyright: 'Copyright &copy; 2015 Carry.Us.Org. All Rights Reserved.'
# credits: '<a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
include: [_data]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
favicon: /img/carryusorg-logo-256.png

social:
  username: carryusorg
  hashtag: athletes4good
  tag: Adventures 
  accounts:
    - title: facebook
      url: https://www.facebook.com/carryusorg
      hashtagurl: https://www.facebook.com/search/top/?q=%23athletes4good
    - title: twitter
      url: https://twitter.com/carryusorg
      hashtagurl: https://twitter.com/hashtag/athletes4good
    - title: instagram
      url: https:instagram.com/carryusorg
      hashtagurl: https://www.instagram.com/explore/tags/athletes4good
    # - title: github
      # url: https://github.com/carryusorg

email:
  - hello@carry.us.org

# front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      opengraph:
        # -
        #   property: url
        #   content: http://carry.us.org
        # -
        #   property: title
        #   content: Carry.Us.Org
        # -
        #   property: image
        #   content: http://carry.us.org/img/twin-peaks-runner.jpg
        # -
        #   property: image
        #   content: http://carry.us.org/img/twin-peaks-runner.jpg

