features:
  -
    title: Campaign Reimbursement & Incentives
    img: /img/women-desert-mtb-win.jpg
    description: |
      Let's face it, independent fundraising is a lot of hard work. Many over taxed and 
      under funded charities hope that enthusiastic and big hearted supporters would
      be happy to shoulder this burden. While most of us are enthusiastic and big 
      hearted, it would still be nice to see independent fundraisers rewarded for their 
      efforts. Here's how we see it:

      - athletes can state their campaign expenses alongside the funding goals for every new campaign
      - these campaign expenses can be reimbursed by tips given transparently during the donation process
      - high value campaigns, and the athletes that run them, are rewarded with incentives
      - these incentives may be virtual badges and/or real valuable gifts
      - incentive gifts are solicited from sponsoring nonprofit and for-profit corporations
  - 
    title: Athlete Fundraising Toolset
    img: /img/brazilian-runner.jpg
    description: |
      Athletic fundraisers are unique to all others in that there is a measurable challenge
      that one endeavors to overcome in order to inspire others to give. With the right tools
      and creativity, an athlete can leverage these challenging experience to inspire 
      thousands of others in support of her cause. With our suite of communication and 
      outreach tools, Carry.Us.Org brings these challenges to life.

      - campaign microsites to promote your cause and your fundraising progress
      - a mobile app to track your athletic progress and update your campaign story
      - recieve donations on your phone or on your microsite
      - collect donor information on your phone of or on your microsite
      - send emails and post social media updates
      - ect... 
  - 
    title: Charity Relationship Management 
    img: /img/mt-kenya-epik.jpg
    description: |
      Charitable organizations are typically over worked and under staffed. 
      It's no wonder that they don't have the time or resources to cater to
      the varying needs of independent fundraisers. That's where Cary.Us.Org 
      fits in. We will negotiate on the athletes behalf, to secure a relationship
      that benefits all parties. Bellow are some examples of the discussions we are having: 
    
      - a single point of contact within the charity organization to smooth communications
      - the use of prominent charity branding to legitimatize an athlete's campaign 
      - the ability to fundraise for individual projects within the charity
      - solicitation of incentive gifts for high value campaigns
      - ect…

pricing:
  title: Campaign Pricing
  description: |
    Carry.Us.Org is funded only by tips. **We will never charge a service fee to the athletes, 
    or take a cut from the donations raised**{:.text-warning}. For each active campaign, 
    we deduct a single flat fee from the campaign reimbursement tips. This fee is calculated 
    as a percentage of the campaign's stated funding goal. If not enough tips are 
    collected to cover the whole fee, the remainder will be waived. 
  features:
    - Charity Relationship Management
    - Athlete Fundraising Toolset
    - Campaign Reimbursement & Incentives
    - Collaborative Campaign Mangement 
    - Professional Athlete Promotion
  footnotes: 
    - "* This fee is is deducted from the campaign tips, and calculated as a percentage of the campaign's funding goal."
  levels:
    -
      title: Independent Campaign
      highlight: true
      img: /img/brazilian-runner.jpg
      fee: 5% *
      availability: Open to all
      features:
        - true
        - true
        - true
    - 
      title: Collaborative Campaign
      img: /img/mt-kenya-epik.jpg
      fee: Contact Us
      availability: Invite Only
      features:
        - true
        - true
        - true
        - true
        - true

     