features:
  -
    title: Campaign Reimbursement & Incentives
    img: /img/women-desert-mtb-win.jpg
    description: |
      the difference between a one time runner and a sustained fundraiser
    benefits:
      - itemize athlete expenses for any campaign
      - expenses will be reimbursed by campaign tips 
      - tips are given transparently during the donation process
      - high value campaigns are rewarded with incentives
      - incentives are virtual badges and real valuable gifts
  - 
    title: Fundraising Tools for Athletes
    img: /img/muddy-rope-racer.jpg
    description: |
      to inspire thousands of others in support of thier causes
    benefits:
      - a microsites to promote the campaign
      - a mobile app for athletes to track their progress
      - collect donations in person or on the web
      - collect and leverage donor data to maximize impact
      - reach out with integrated email and social media updates
      - ect... 
  - 
    title: Charity Relationship Management 
    img: /img/continental-divide-horseback.jpg
    description: |
      to get the most benefit from independent fundraising. 
    benefits:
      - a single point of contact for charity communications
      - effective charity branding to legitimatize each campaign 
      - targeted fundraising projects within each charity
      - solicitation of incentive gifts for high value campaigns
      - ect…

pricing:
  title: Campaign Pricing
  description: |
    Carry.Us.Org is funded only by tips, which are shared with the athlete to 
    to cover campaign expenses.  
    <big class="text-warning">We will never charge a fee to the athletes, 
    or take a cut from the donations raised.</big>
  features:
    - Campaign Reimbursement & Incentives
    - Fundraising Tools for Athletes
    - Charity Relationship Management
  footnotes: 
    - "* Each athlete will be offered a share of the tips given, until their campaign expenses are fully reimbursed."
  levels:
    -
      title: Alpha Pre-Release 
      highlight: warning
      img: /img/brazilian-runner.jpg
      invite: true
      availability: July 2016
      fee: No Fee
      tips: 100%
      features:
        - true
        - 
        - false
    -
      title: Independent Campaign
      highlight: primary
      img: /img/brazilian-runner.jpg
      availability: true
      fee: No Fee
      tips: 50%
      features:
        - true
        - true
        - true


     