-
  img: /img/amgen-tour-doggy.jpg
  title: Collaboration
  description: | 
     We will work with your chosen charities to develop the support system you need.

-
  img: /img/brazilian-runner.jpg
  title: Communication
  description: | 
     We are developing a multichannel toolset for you to engage with a wide donor base.

-
  img: /img/swimmer-in-the-night.jpg
  title: Reimbursement
  description: | 
     You will be able to fund your own campaign expenses, without deducting from the donations.

-
  img: /img/row-boat-calm-water.jpg
  title: Delivery
  description: | 
     We will handle the secure delivery and receipting of all charitable donations and campaign tips. 

-
  img: /img/mt-kenya-epik.jpg
  title: Incentives
  description: | 
     We encourage high quality participation by awarding medals and valuable rewards to every athlete.

-
  img: /img/muddy-rope-racer.jpg
  title: Independence
  description: | 
     We support you to create your own fundraising campaign, of your own design and on your own terms.

-
  img: /img/climber-in-the-french-alps.jpg
  title: No Charge To You
  description: | 
     We will not charge you for this service nor will we deduct from the donations you raise.
-
  img: /img/trail-runner-legs.jpg
  title: Transparency
  description: | 
     As a benefit corporation [*](http://benefitcorp.net/), our mission is to serve you and the charities you support.
  
